// Generated by CoffeeScript 1.12.7
(function() {
  var FirmListAdminCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  FirmListAdminCtrl = (function(superClass) {
    extend(FirmListAdminCtrl, superClass);

    function FirmListAdminCtrl() {
      return FirmListAdminCtrl.__super__.constructor.apply(this, arguments);
    }

    FirmListAdminCtrl.prototype.events = {
      "load article#list-firm": "loadFirm",
      "singleTap a[data-action=new]": "onNewFirm"
    };

    FirmListAdminCtrl.prototype.elements = {
      "#list-firm": "listFirm",
      "#header_list_text": "header"
    };

    FirmListAdminCtrl.prototype.onNewFirm = function(event) {
      if (this.listFirm.hasClass("active")) {
        return __FacadeCore.Router_section("newFirm");
      }
    };

    FirmListAdminCtrl.prototype.loadFirm = function(event) {
      var _this, url;
      this.header.html(AppAdmin.firmDomain + " - " + findLangTextElement("label.aside.firms"));
      Lungo.Element.loading("#list-firm ul", "black");
      url = "http://" + appHost + "/firm/admin/list";
      _this = this;
      return $$.json(url, null, function(response) {
        return _this.showFirm(response);
      });
    };

    FirmListAdminCtrl.prototype.showFirm = function(response) {
      var firEnabled, firm, firmAux, i, len, result, results, textsTemplates, view;
      if (response.length > 0) {
        result = Lungo.Core.toArray(response);
        result = Lungo.Core.orderByProperty(result, "firName", "asc");
        this.listFirm.children().empty();
        textsTemplates = {
          enabled: findLangTextElement("form.enabled")
        };
        results = [];
        for (i = 0, len = result.length; i < len; i++) {
          firmAux = result[i];
          firEnabled = false;
          textsTemplates = {
            enabled: findLangTextElement("form.closed")
          };
          if (firmAux.enabled === 1) {
            firEnabled = true;
            textsTemplates.enabled = findLangTextElement("form.enabled");
          }
          firm = new __Model.Firm({
            enabled: firEnabled,
            firId: firmAux.id,
            firName: firmAux.firName,
            firDomain: firmAux.firDomain,
            firServer: firmAux.firServer,
            firResponName: firmAux.firRespon.whoName,
            firResponSurname: firmAux.firRespon.whoSurname,
            firResponEmail: firmAux.firRespon.whoEmail,
            firResponTelf1: firmAux.firRespon.whoTelf1,
            firAddress: firmAux.firWhere.wheAddress,
            firCity: firmAux.firWhere.wheCity,
            firState: firmAux.firWhere.wheState,
            firCP: firmAux.firWhere.wheCP,
            firCountry: firmAux.firWhere.wheCountry,
            firClassTasks: firmAux.firClassTasks,
            firGwtUsers: firmAux.firGwtUsers,
            firBilledModule: firmAux.firBilledModule,
            firConfig: firmAux.firConfig.numConfig,
            texts: textsTemplates
          });
          view = new __View.FirmListAdminView({
            model: firm
          });
          results.push(view.append(firm));
        }
        return results;
      } else {
        this.listFirm.children().empty();
        return Lungo.Notification.success(findLangTextElement("label.notification.noData.title"), findLangTextElement("label.notification.noData.text"), null, 3);
      }
    };

    return FirmListAdminCtrl;

  })(Monocle.Controller);

  __Controller.FirmListAdmin = new FirmListAdminCtrl("section#admin");

}).call(this);
