// Generated by CoffeeScript 1.12.7
(function() {
  var EventCancelCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventCancelCtrl = (function(superClass) {
    extend(EventCancelCtrl, superClass);

    function EventCancelCtrl() {
      return EventCancelCtrl.__super__.constructor.apply(this, arguments);
    }

    EventCancelCtrl.prototype.events = {
      "singleTap a[data-action=save]": "onSave",
      "singleTap a[data-action=cancel]": "onCancel",
      "load #cancelEvent": "loadCancel",
      "unload #cancelEvent": "unloadCancel",
      "change #eveCancelSend": "changeEveCancelSend"
    };

    EventCancelCtrl.prototype.elements = {
      "#eveCancelText": "eveCancelText",
      "#eveCancelSend": "eveCancelSend",
      "a[data-action=save]": "buttonSave",
      "a[data-action=cancel]": "buttonCancel",
      "#event_hour": "eventHour",
      "#error_eveClientEmail": "errorEveClientEmail"
    };

    EventCancelCtrl.prototype.loadCancel = function(event) {
      var dateHour, eventCancel, hourApo, mail;
      this.eveCancelSend.val("1");
      this.eveCancelText.val("");
      this.eveCancelText[0].disabled = false;
      eventCancel = __FacadeCore.Cache_get(appName + "eventCancel");
      mail = eventCancel.eveClient.whoEmail;
      if (!mail || mail.length === 0) {
        this.errorEveClientEmail.html(findLangTextElement("event.cancelNotEmail"));
        this.eveCancelSend[0].options[1].selected = true;
        this.eveCancelSend[0].disabled = true;
        this.eveCancelText[0].disabled = true;
      } else {
        this.errorEveClientEmail.html("");
        this.eveCancelSend[0].options[0].selected = true;
        this.eveCancelSend[0].disabled = false;
        this.eveCancelText[0].disabled = false;
      }
      dateHour = new Date(eventCancel.eveStartTime);
      hourApo = dateToStringFormat(dateHour) + " " + dateToStringHour(dateHour) + " - " + eventCancel.eveClient.whoName;
      return this.eventHour.html(hourApo);
    };

    EventCancelCtrl.prototype.changeEveCancelSend = function(event) {
      if (this.eveCancelSend.val() === "1") {
        return this.eveCancelText[0].disabled = false;
      } else {
        return this.eveCancelText[0].disabled = true;
      }
    };

    EventCancelCtrl.prototype.onSave = function(event) {
      var _this, data, eventCancel, local, url;
      __FacadeCore.Cache_remove(appName + "elementSave");
      __FacadeCore.Cache_remove(appName + "elementCancel");
      __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
      __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
      Lungo.Element.loading(this.buttonSave.selector, "black");
      Lungo.Element.loading(this.buttonCancel.selector, "black");
      eventCancel = __FacadeCore.Cache_get(appName + "eventCancel");
      url = "http://" + appHost + "/event/operator/cancel";
      local = __FacadeCore.Cache_get(appName + "local");
      data = {
        localId: local.id,
        id: eventCancel.eveId,
        send: this.eveCancelSend.val(),
        text: this.eveCancelText.val()
      };
      _this = this;
      return $$.put(url, data, function() {
        return Lungo.Notification.success(findLangTextElement("label.notification.canceledApo.title"), findLangTextElement("label.notification.canceledApo.text"), null, 3, function(response) {
          __Controller.EventList.setResult(null);
          return __FacadeCore.Router_article("booking", "list-events");
        });
      });
    };

    EventCancelCtrl.prototype.onCancel = function(event) {
      __FacadeCore.Cache_remove(appName + "elementSave");
      __FacadeCore.Cache_remove(appName + "elementCancel");
      __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
      __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
      Lungo.Element.loading(this.buttonSave.selector, "black");
      Lungo.Element.loading(this.buttonCancel.selector, "black");
      return __FacadeCore.Router_back();
    };

    EventCancelCtrl.prototype.resetArticle = function() {
      this.buttonSave.html(__FacadeCore.Cache_get(appName + "elementSave"));
      this.buttonCancel.html(__FacadeCore.Cache_get(appName + "elementCancel"));
      return this.eveCancelText.val("");
    };

    EventCancelCtrl.prototype.unloadCancel = function(event) {
      this.resetArticle();
      return __FacadeCore.Cache_remove(appName + "eventCancel");
    };

    return EventCancelCtrl;

  })(Monocle.Controller);

  __Controller.EventCancel = new EventCancelCtrl("section#cancelEvent");

}).call(this);
