// Generated by CoffeeScript 1.12.7
(function() {
  var EventFinCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventFinCtrl = (function(superClass) {
    extend(EventFinCtrl, superClass);

    function EventFinCtrl() {
      return EventFinCtrl.__super__.constructor.apply(this, arguments);
    }

    EventFinCtrl.prototype.events = {
      "singleTap a[data-action=save]": "onSave",
      "singleTap a[data-action=cancel]": "onCancel",
      "load #finEvent": "loadFin",
      "unload #finEvent": "unloadFin"
    };

    EventFinCtrl.prototype.elements = {
      "#eveFinText": "eveFinText",
      "#eveFinSel": "eveFinSel",
      "a[data-action=save]": "buttonSave",
      "a[data-action=cancel]": "buttonCancel",
      "#event_hour": "eventHour"
    };

    EventFinCtrl.prototype.loadFin = function(event) {
      var dateHour, eventFin, hourApo;
      this.eveFinSel.val("1");
      this.eveFinText.val("");
      this.eveFinText[0].disabled = false;
      eventFin = __FacadeCore.Cache_get(appName + "eventFin");
      this.eveFinSel[0].options[0].selected = true;
      dateHour = new Date(eventFin.eveStartTime);
      hourApo = dateToStringFormat(dateHour) + " " + dateToStringHour(dateHour) + " - " + eventFin.eveClient.whoName;
      return this.eventHour.html(hourApo);
    };

    EventFinCtrl.prototype.onSave = function(event) {
      var _this, data, eventFin, url;
      __FacadeCore.Cache_remove(appName + "elementSave");
      __FacadeCore.Cache_remove(appName + "elementCancel");
      __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
      __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
      Lungo.Element.loading(this.buttonSave.selector, "black");
      Lungo.Element.loading(this.buttonCancel.selector, "black");
      eventFin = __FacadeCore.Cache_get(appName + "eventFin");
      url = "http://" + appHost + "/event/operator/consumeComent";
      data = {
        ICS: eventFin.eveICS,
        sel: this.eveFinSel.val(),
        text: this.eveFinText.val()
      };
      _this = this;
      return $$.put(url, data, function() {
        __Controller.EventList.setResult(null);
        return __FacadeCore.Router_article("booking", "list-events");
      });
    };

    EventFinCtrl.prototype.onCancel = function(event) {
      __FacadeCore.Cache_remove(appName + "elementSave");
      __FacadeCore.Cache_remove(appName + "elementCancel");
      __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
      __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
      Lungo.Element.loading(this.buttonSave.selector, "black");
      Lungo.Element.loading(this.buttonCancel.selector, "black");
      return __FacadeCore.Router_back();
    };

    EventFinCtrl.prototype.resetArticle = function() {
      this.buttonSave.html(__FacadeCore.Cache_get(appName + "elementSave"));
      this.buttonCancel.html(__FacadeCore.Cache_get(appName + "elementCancel"));
      return this.eveFinText.val("");
    };

    EventFinCtrl.prototype.unloadFin = function(event) {
      this.resetArticle();
      return __FacadeCore.Cache_remove(appName + "eventFin");
    };

    return EventFinCtrl;

  })(Monocle.Controller);

  __Controller.EventFin = new EventFinCtrl("section#finEvent");

}).call(this);
