// Generated by CoffeeScript 1.12.7
(function() {
  var ProductNewCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ProductNewCtrl = (function(superClass) {
    extend(ProductNewCtrl, superClass);

    function ProductNewCtrl() {
      return ProductNewCtrl.__super__.constructor.apply(this, arguments);
    }

    ProductNewCtrl.prototype.events = {
      "load #product-form": "loadNew",
      "singleTap a[data-action=save]": "onSave",
      "singleTap a[data-action=cancel]": "onCancel",
      "change #proRate": "changeRate"
    };

    ProductNewCtrl.prototype.elements = {
      "#product-form": "productForm",
      "a[data-action=save]": "buttonSave",
      "a[data-action=cancel]": "buttonCancel",
      "a[data-action=new]": "buttonNew",
      "#product-name": "proNameInputContainer",
      "#proNameError": "proNameError",
      "#proRate": "proRate",
      "#proRateError": "proRateError",
      "#symbol_currency": "symbolCurrency"
    };

    ProductNewCtrl.prototype.changeRate = function(event) {
      return this.proRate.val(parseFloat(this.proRate.val()).toFixed(2));
    };

    ProductNewCtrl.prototype.loadNew = function(event) {
      var asyn, data, i, j, k, lang, len, len1, local, localLang, localLangs, nameMulti, nameMultiResult, nameMultiText, product, results, url, view;
      this.buttonNew.hide();
      product = __FacadeCore.Cache_get(appName + "productNew");
      local = __FacadeCore.Cache_get(appName + "local");
      this.symbolCurrency.html(local.locWhere.wheCurrency);
      localLangs = Lungo.Core.toArray(local.locLangs);
      localLangs = Lungo.Core.orderByProperty(localLangs, "lanName", "asc");
      lang = Lungo.Core.findByProperty(localLangs, "lanCode", langApp);
      localLangs = changeArrayToFirst(localLangs, lang);
      if (product) {
        asyn = __FacadeCore.Service_Settings_asyncFalse();
        url = "http://" + appHost + "/multiText/listByKey";
        data = {
          key: product.proNameMulti
        };
        nameMultiResult = $$.json(url, data);
        __FacadeCore.Service_Settings_async(asyn);
        nameMulti = Lungo.Core.toArray(nameMultiResult);
        nameMulti = Lungo.Core.orderByProperty(nameMulti, "mulLanName", "asc");
        lang = Lungo.Core.findByProperty(nameMulti, "mulLanCode", langApp);
        nameMulti = changeArrayToFirst(nameMulti, lang);
        this.proRate.val(parseFloat(product.proRate).toFixed(2));
      } else {
        nameMulti = new Array();
        i = -1;
        for (j = 0, len = localLangs.length; j < len; j++) {
          localLang = localLangs[j];
          i++;
          nameMultiText = {
            mulLanName: localLang.lanName,
            mulLanCode: localLang.lanCode
          };
          nameMulti[i] = nameMultiText;
        }
        this.proRate.val("");
      }
      this.proNameInputContainer.empty();
      results = [];
      for (k = 0, len1 = nameMulti.length; k < len1; k++) {
        nameMultiText = nameMulti[k];
        if (!product || (product && Lungo.Core.findByProperty(localLangs, "lanCode", nameMultiText.mulLanCode))) {
          view = new __View.ProductNameView({
            model: nameMultiText
          });
          results.push(view.append(nameMultiText));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    ProductNewCtrl.prototype.onSave = function(event) {
      var _this, data, local, proNameInput, product, url;
      if (this.validateForm()) {
        __FacadeCore.Cache_remove(appName + "elementSave");
        __FacadeCore.Cache_remove(appName + "elementCancel");
        __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
        __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
        Lungo.Element.loading(this.buttonSave.selector, "black");
        Lungo.Element.loading(this.buttonCancel.selector, "black");
        product = __FacadeCore.Cache_get(appName + "productNew");
        local = __FacadeCore.Cache_get(appName + "local");
        data = {
          localId: local.id,
          proRate: this.proRate.val()
        };
        proNameInput = $$("#product-name input[type=text]");
        proNameInput.each(function() {
          return eval("data." + $$(this)[0].id + " = '" + $$(this).val() + "'");
        });
        if (product) {
          data.id = product.proId;
        }
        url = "http://" + appHost + "/product/manager/new";
        _this = this;
        return $$.put(url, data, function(response) {
          return Lungo.Notification.success(findLangTextElement("label.notification.salvedData.title"), findLangTextElement("label.notification.salvedData.text"), null, 3, function() {
            __FacadeCore.Router_article("booking", "list-product");
            return _this.resetArticle();
          });
        });
      }
    };

    ProductNewCtrl.prototype.validateForm = function() {
      var _this, proNameInput, result;
      result = true;
      this.proNameError.html("");
      this.proRateError.html("");
      proNameInput = $$("#product-name input[type=text]");
      _this = this;
      proNameInput.each(function() {
        if (result && !$$(this)[0].checkValidity()) {
          _this.proNameError.html(getMessageValidity($$(this)[0]));
          $$(this)[0].focus();
          return result = false;
        }
      });
      if (result && !checkValidity(this.proRate.val(), this.proRate.attr("pattern"), this.proRate.attr("required"))) {
        this.proRateError.html(getMessageValidity(this.proRate[0]));
        this.proRate[0].focus();
        result = false;
      }
      return result;
    };

    ProductNewCtrl.prototype.onCancel = function(event) {
      if (this.productForm.hasClass("active")) {
        __FacadeCore.Cache_remove(appName + "elementSave");
        __FacadeCore.Cache_remove(appName + "elementCancel");
        __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
        __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
        Lungo.Element.loading(this.buttonSave.selector, "black");
        Lungo.Element.loading(this.buttonCancel.selector, "black");
        __FacadeCore.Router_article("booking", "list-product");
        return this.resetArticle();
      }
    };

    ProductNewCtrl.prototype.resetArticle = function() {
      this.buttonSave.html(__FacadeCore.Cache_get(appName + "elementSave"));
      this.buttonCancel.html(__FacadeCore.Cache_get(appName + "elementCancel"));
      this.proNameError.html("");
      this.proRateError.html("");
      return __FacadeCore.Cache_remove(appName + "productNew");
    };

    return ProductNewCtrl;

  })(Monocle.Controller);

  __Controller.ProductNew = new ProductNewCtrl("section#newProduct");

}).call(this);
