// Generated by CoffeeScript 1.12.7
(function() {
  var ReportSalesCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ReportSalesCtrl = (function(superClass) {
    extend(ReportSalesCtrl, superClass);

    function ReportSalesCtrl() {
      return ReportSalesCtrl.__super__.constructor.apply(this, arguments);
    }

    ReportSalesCtrl.prototype.events = {
      "load article#report-sales": "loadReport",
      "singleTap a[data-action=send]": "onSend",
      "singleTap #report-sales #report-range": "loadRange"
    };

    ReportSalesCtrl.prototype.elements = {
      "header a[href=\\#]": "header",
      "header a[href=\\#menu]": "aside",
      "footer a": "footer",
      "a[data-action=send]": "buttonSend",
      "#report-sales": "artReport",
      "#report-range": "reportRangeTimes",
      "#report-sales #all-table": "reportAllTable",
      "#report-sales #all-pie": "reportAllPie",
      "#report-sales #task-table": "reportTaskTable",
      "#report-sales #task-column1": "reportTaskColumn1",
      "#report-sales #product-table": "reportProductTable",
      "#report-sales #product-column1": "reportProductColumn1"
    };

    ReportSalesCtrl.prototype.loadRange = function(event) {
      return __FacadeCore.Router_article("rangeSelect", "range-form");
    };

    ReportSalesCtrl.prototype.loadReport = function(event) {
      var _this, data, local, selectedRangeTimes, strRange, url;
      this.header.show();
      this.aside.show();
      this.footer.show();
      selectedRangeTimes = __FacadeCore.Cache_get(appName + "selectedRangeTimes");
      if (selectedRangeTimes) {
        strRange = dateToStringFormat(stringToDate(selectedRangeTimes.start)) + " - " + dateToStringFormat(stringToDate(selectedRangeTimes.end));
        strRange += ". " + findLangTextElement("label.html.apoFor3") + ".";
        this.reportRangeTimes.html(strRange);
        url = "http://" + appHost + "/report/manager/sales/all";
        local = __FacadeCore.Cache_get(appName + "local");
        data = {
          localId: local.id,
          selectedDateStart: selectedRangeTimes.start,
          selectedDateEnd: selectedRangeTimes.end
        };
        _this = this;
        return $$.json(url, data, function(responseAll) {
          url = "http://" + appHost + "/report/manager/sales/task";
          return $$.json(url, data, function(responseTask) {
            url = "http://" + appHost + "/report/manager/sales/product";
            return $$.json(url, data, function(responseProduct) {
              return _this.showReport(responseAll, responseTask, responseProduct);
            });
          });
        });
      } else {
        this.reportRangeTimes.html("");
        return Lungo.Notification.success(findLangTextElement("report.notification.selectRange.title"), findLangTextElement("report.notification.selectRange.text"), null, 3, function(response) {
          return __FacadeCore.Router_article("rangeSelect", "range-form");
        });
      }
    };

    ReportSalesCtrl.prototype.showReport = function(responseAll, responseTask, responseProduct) {
      var chartColumn, chartPie, chartTable, data, formatter, local, strCab, total, view;
      local = __FacadeCore.Cache_get(appName + "local");
      data = new google.visualization.DataTable(responseAll);
      formatter = new google.visualization.NumberFormat({
        suffix: " " + local.locWhere.wheCurrency
      });
      formatter.format(data, 1);
      total = responseAll.rows[0].c[1].v;
      chartTable = new google.visualization.Table(this.reportAllTable[0]);
      chartTable.draw(data, {
        sortColumn: 1,
        sortAscending: false
      });
      view = new google.visualization.DataView(data);
      view.hideRows([0]);
      strCab = findLangTextElement("report.sales.totalAll.cab");
      strCab += ": " + total;
      chartPie = new google.visualization.PieChart(this.reportAllPie[0]);
      chartPie.draw(view, {
        title: strCab,
        backgroundColor: "#f4f5f0"
      });
      data = new google.visualization.DataTable(responseTask);
      formatter.format(data, 1);
      data.sort([
        {
          column: 1,
          desc: true
        }, {
          column: 0
        }
      ]);
      chartTable = new google.visualization.Table(this.reportTaskTable[0]);
      chartTable.draw(data);
      total = responseTask.rows[0].c[1].v;
      view = new google.visualization.DataView(data);
      view.hideRows([0]);
      strCab = findLangTextElement("report.sales.totalTask.cab");
      strCab += ": " + total + " " + local.locWhere.wheCurrency;
      chartColumn = new google.visualization.ColumnChart(this.reportTaskColumn1[0]);
      chartColumn.draw(view, {
        title: strCab,
        backgroundColor: "#f4f5f0",
        colors: ["#2f886b"]
      });
      data = new google.visualization.DataTable(responseProduct);
      data.sort([
        {
          column: 1,
          desc: true
        }, {
          column: 0
        }
      ]);
      formatter.format(data, 1);
      chartTable = new google.visualization.Table(this.reportProductTable[0]);
      chartTable.draw(data);
      total = responseProduct.rows[0].c[1].v;
      view = new google.visualization.DataView(data);
      view.hideRows([0]);
      strCab = findLangTextElement("report.sales.totalProduct.cab");
      strCab += ": " + total + " " + local.locWhere.wheCurrency;
      chartColumn = new google.visualization.ColumnChart(this.reportProductColumn1[0]);
      return chartColumn.draw(view, {
        title: strCab,
        backgroundColor: "#f4f5f0",
        colors: ["#2f886b"]
      });
    };

    ReportSalesCtrl.prototype.onSend = function(event) {
      var content, data, local, selectedRangeTimes, url;
      url = "http://" + appHost + "/report/manager/send";
      selectedRangeTimes = __FacadeCore.Cache_get(appName + "selectedRangeTimes");
      content = this.reportTaskTable.html() + this.reportProductTable.html();
      local = __FacadeCore.Cache_get(appName + "local");
      data = {
        localId: local.id,
        selectedDateStart: selectedRangeTimes.start,
        selectedDateEnd: selectedRangeTimes.end,
        content: content
      };
      return $$.post(url, data, function() {
        return Lungo.Notification.success(findLangTextElement("report.notification.mail.send.title"), findLangTextElement("report.notification.mail.send.text"), null, 3);
      });
    };

    return ReportSalesCtrl;

  })(Monocle.Controller);

  __Controller.ReportSales = new ReportSalesCtrl("section#booking");

}).call(this);
