// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.Calendar = (function(superClass) {
    extend(Calendar, superClass);

    function Calendar() {
      return Calendar.__super__.constructor.apply(this, arguments);
    }

    Calendar.fields("calId", "calLocalId", "calEventDuration", "calTimeRestricted", "calName", "calDesc", "calProf", "calLocalTasks", "calLocalTasksId", "calDiaryMon", "calDiaryTue", "calDiaryWed", "calDiaryThu", "calDiaryFri", "calDiarySat", "calDiarySun", "calSemanalDiary");

    return Calendar;

  })(__Model.General);

}).call(this);
