// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.Firm = (function(superClass) {
    extend(Firm, superClass);

    function Firm() {
      return Firm.__super__.constructor.apply(this, arguments);
    }

    Firm.fields("firId", "firName", "firDomain", "firServer", "firResponName", "firResponSurname", "firResponEmail", "firResponTelf1", "firWhere", "firClassTasks", "firGwtUsers", "firBilledModule", "firConfig");

    return Firm;

  })(__Model.General);

}).call(this);
