// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.General = (function(superClass) {
    extend(General, superClass);

    function General() {
      return General.__super__.constructor.apply(this, arguments);
    }

    General.fields("enabled", "router", "texts");

    return General;

  })(Monocle.Model);

}).call(this);
