// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.Invoice = (function(superClass) {
    extend(Invoice, superClass);

    function Invoice() {
      return Invoice.__super__.constructor.apply(this, arguments);
    }

    Invoice.fields("invId", "invRate", "invTime", "invClient", "eveDay", "eveHour", "invDesc", "invBilleds", "invRateDay");

    return Invoice;

  })(__Model.General);

}).call(this);
