// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.Local = (function(superClass) {
    extend(Local, superClass);

    function Local() {
      return Local.__super__.constructor.apply(this, arguments);
    }

    Local.fields("locId", "locBookingClient", "locName", "locLocation", "locTimeRestricted", "locOpenDays", "locNumPersonsApo", "locNumUsuDays", "locSelect");

    return Local;

  })(__Model.General);

}).call(this);
