// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.LocalTask = (function(superClass) {
    extend(LocalTask, superClass);

    function LocalTask() {
      return LocalTask.__super__.constructor.apply(this, arguments);
    }

    LocalTask.fields("lotId", "lotLocalId", "lotTaskId", "lotNameMulti", "lotTaskDuration", "lotTaskPost", "lotTaskRate", "hasLotTaskRate", "lotName", "lotDefault", "lotTaskCombiIdFirst", "lotTaskCombiIdSecond", "lotTaskCombiRes", "lotVisible");

    return LocalTask;

  })(__Model.General);

}).call(this);
