// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.TaskSel = (function(superClass) {
    extend(TaskSel, superClass);

    function TaskSel() {
      return TaskSel.__super__.constructor.apply(this, arguments);
    }

    TaskSel.fields("tasSelId", "tasSelName", "tasMultiple", "tasGoodsNumLines", "tasGoodsNumPallets");

    return TaskSel;

  })(__Model.General);

}).call(this);
