// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __Model.TimesHours = (function(superClass) {
    extend(TimesHours, superClass);

    function TimesHours() {
      return TimesHours.__super__.constructor.apply(this, arguments);
    }

    TimesHours.fields("timId", "timFrom", "timUntil", "timDay");

    return TimesHours;

  })(__Model.General);

}).call(this);
