// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.BilledView = (function(superClass) {
    extend(BilledView, superClass);

    function BilledView() {
      return BilledView.__super__.constructor.apply(this, arguments);
    }

    BilledView.prototype.container = "section#newInvoice article#invoice-form ul";

    BilledView.prototype.template_url = "/app/templates/billed.mustache";

    BilledView.prototype.events = {
      "singleTap div[data-id=divBilTaskId]": "onTasksInv",
      "singleTap button": "onRemove"
    };

    BilledView.prototype.onTasksInv = function(event) {
      var objSelect, type;
      __Controller.InvoiceNew.conserveData = true;
      __FacadeCore.Cache_remove(appName + "selectedTasksBilNum");
      __FacadeCore.Cache_set(appName + "selectedTasksBilNum", this.model.bilId);
      objSelect = Lungo.dom("#invoice-form #bilTaskId" + this.model.bilId);
      type = 0;
      if (objSelect.attr("data-product")) {
        type = 1;
      }
      __FacadeCore.Cache_remove(appName + "selectedTasksBilType");
      __FacadeCore.Cache_set(appName + "selectedTasksBilType", type);
      return __FacadeCore.Router_article("newInvoice", "invoiceTaskSelect-form");
    };

    BilledView.prototype.onRemove = function(event) {
      this.remove();
      __FacadeCore.Cache_remove(appName + "bilTaskId" + this.model.bilId);
      return __Controller.InvoiceNew.changeRate(event);
    };

    return BilledView;

  })(Monocle.View);

}).call(this);
