// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.BookingDaySPView = (function(superClass) {
    extend(BookingDaySPView, superClass);

    function BookingDaySPView() {
      return BookingDaySPView.__super__.constructor.apply(this, arguments);
    }

    BookingDaySPView.prototype.container = "section#booking article#table-day div#table-day-container";

    BookingDaySPView.prototype.template_url = "/app/templates/bookingDaySP.mustache";

    BookingDaySPView.prototype.events = {
      "singleTap div": "onTap"
    };

    BookingDaySPView.prototype.onTap = function(event) {
      var calendarSel, selectedCalendars;
      __FacadeCore.Cache_remove(appName + "newApo");
      __FacadeCore.Cache_set(appName + "newApo", this.model);
      selectedCalendars = new Array();
      calendarSel = {
        id: this.model.apoCalendarId,
        name: this.model.apoCalendarName
      };
      selectedCalendars[0] = calendarSel;
      __FacadeCore.Cache_remove(appName + "selectedCalendars");
      __FacadeCore.Cache_set(appName + "selectedCalendars", selectedCalendars);
      return __FacadeCore.Router_section("#newEvent");
    };

    return BookingDaySPView;

  })(Monocle.View);

}).call(this);
