// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.CalendarSelectView = (function(superClass) {
    extend(CalendarSelectView, superClass);

    function CalendarSelectView() {
      return CalendarSelectView.__super__.constructor.apply(this, arguments);
    }

    CalendarSelectView.prototype.container = "section#calendarDiarySelect article#calendarDiary-form ul";

    CalendarSelectView.prototype.template_url = "/app/templates/calendarSelect.mustache";

    CalendarSelectView.prototype.events = {
      "singleTap li": "onSelect"
    };

    CalendarSelectView.prototype.onSelect = function(event) {
      this.model.updateAttributes({
        enabled: this.model.enabled ? false : true
      });
      return this.refresh();
    };

    return CalendarSelectView;

  })(Monocle.View);

}).call(this);
