// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.ClientSearchListView = (function(superClass) {
    extend(ClientSearchListView, superClass);

    function ClientSearchListView() {
      return ClientSearchListView.__super__.constructor.apply(this, arguments);
    }

    ClientSearchListView.prototype.container = "section#searchClient article#search-clients ul";

    ClientSearchListView.prototype.template_url = "/app/templates/clientList.mustache";

    ClientSearchListView.prototype.events = {
      "singleTap li": "selectClient"
    };

    ClientSearchListView.prototype.selectClient = function(event) {
      var router;
      router = __FacadeCore.Cache_get(appName + "routerSearchClient");
      __FacadeCore.Cache_remove(appName + "routerSearchClient");
      __FacadeCore.Cache_remove(appName + "selectClient");
      __FacadeCore.Cache_set(appName + "selectClient", this.model);
      return __FacadeCore.Router_section(router);
    };

    return ClientSearchListView;

  })(Monocle.View);

}).call(this);
