// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.EventListUntilView = (function(superClass) {
    extend(EventListUntilView, superClass);

    function EventListUntilView() {
      return EventListUntilView.__super__.constructor.apply(this, arguments);
    }

    EventListUntilView.prototype.container = "section#booking article#list-events ul";

    EventListUntilView.prototype.template_url = "/app/templates/eventsListUntil.mustache";

    EventListUntilView.prototype.events = {
      "singleTap li": "onTap"
    };

    EventListUntilView.prototype.onTap = function(event) {
      return __Controller.EventList.onNext(event);
    };

    return EventListUntilView;

  })(Monocle.View);

}).call(this);
