// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.EventListReadView = (function(superClass) {
    extend(EventListReadView, superClass);

    function EventListReadView() {
      return EventListReadView.__super__.constructor.apply(this, arguments);
    }

    EventListReadView.prototype.container = "section#booking article#list-events ul";

    EventListReadView.prototype.template_url = "/app/templates/eventsList.mustache";

    EventListReadView.prototype.elements = {
      "div:first-child": "divConsumed"
    };

    EventListReadView.prototype.events = {
      "doubleTap li": "consumEvent"
    };

    EventListReadView.prototype.consumEvent = function(event) {
      var view;
      view = new __View.EventListView({
        model: this.model
      });
      return view.consumEvent(event);
    };

    return EventListReadView;

  })(Monocle.View);

}).call(this);
