// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.EventListFromView = (function(superClass) {
    extend(EventListFromView, superClass);

    function EventListFromView() {
      return EventListFromView.__super__.constructor.apply(this, arguments);
    }

    EventListFromView.prototype.container = "section#booking article#list-events ul";

    EventListFromView.prototype.template_url = "/app/templates/eventsListFrom.mustache";

    EventListFromView.prototype.events = {
      "singleTap li": "onTap"
    };

    EventListFromView.prototype.onTap = function(event) {
      return __Controller.EventList.onPrevius(event);
    };

    return EventListFromView;

  })(Monocle.View);

}).call(this);
