// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.EventListDayView = (function(superClass) {
    extend(EventListDayView, superClass);

    function EventListDayView() {
      return EventListDayView.__super__.constructor.apply(this, arguments);
    }

    EventListDayView.prototype.container = "section#booking article#list-events ul";

    EventListDayView.prototype.template_url = "/app/templates/eventsListDay.mustache";

    EventListDayView.prototype.events = {
      "singleTap li": "onTap"
    };

    EventListDayView.prototype.onTap = function(event) {
      var selectedDate;
      selectedDate = dateToString(new Date(this.model.eveStartTime));
      __FacadeCore.Cache_remove(appName + "selectedDateDiary");
      __FacadeCore.Cache_set(appName + "selectedDateDiary", selectedDate);
      return __Controller.EventList.loadListEventsWeek(event);
    };

    return EventListDayView;

  })(Monocle.View);

}).call(this);
