// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.InvoiceListView = (function(superClass) {
    extend(InvoiceListView, superClass);

    function InvoiceListView() {
      return InvoiceListView.__super__.constructor.apply(this, arguments);
    }

    InvoiceListView.prototype.container = "section#booking article#list-invoices ul";

    InvoiceListView.prototype.template_url = "/app/templates/invoicesList.mustache";

    return InvoiceListView;

  })(Monocle.View);

}).call(this);
