// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.InvoiceListDayView = (function(superClass) {
    extend(InvoiceListDayView, superClass);

    function InvoiceListDayView() {
      return InvoiceListDayView.__super__.constructor.apply(this, arguments);
    }

    InvoiceListDayView.prototype.container = "section#booking article#list-invoices ul";

    InvoiceListDayView.prototype.template_url = "/app/templates/invoicesListDay.mustache";

    InvoiceListDayView.prototype.events = {
      "singleTap li": "onTap"
    };

    InvoiceListDayView.prototype.onTap = function(event) {
      var selectedDate;
      selectedDate = dateToString(new Date(this.model.invTime));
      __FacadeCore.Cache_remove(appName + "selectedDateDiary");
      __FacadeCore.Cache_set(appName + "selectedDateDiary", selectedDate);
      return __Controller.InvoiceList.loadListInvoicesWeek(event);
    };

    return InvoiceListDayView;

  })(Monocle.View);

}).call(this);
