// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.InvoiceListUntilView = (function(superClass) {
    extend(InvoiceListUntilView, superClass);

    function InvoiceListUntilView() {
      return InvoiceListUntilView.__super__.constructor.apply(this, arguments);
    }

    InvoiceListUntilView.prototype.container = "section#booking article#list-invoices ul";

    InvoiceListUntilView.prototype.template_url = "/app/templates/eventsListUntil.mustache";

    InvoiceListUntilView.prototype.events = {
      "singleTap li": "onTap"
    };

    InvoiceListUntilView.prototype.onTap = function(event) {
      return __Controller.InvoiceList.onNext(event);
    };

    return InvoiceListUntilView;

  })(Monocle.View);

}).call(this);
