// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.InvoiceNewView = (function(superClass) {
    extend(InvoiceNewView, superClass);

    function InvoiceNewView() {
      return InvoiceNewView.__super__.constructor.apply(this, arguments);
    }

    InvoiceNewView.prototype.container = "section#newInvoice article#invoice-form ul";

    InvoiceNewView.prototype.template_url = "/app/templates/invoiceNew.mustache";

    return InvoiceNewView;

  })(Monocle.View);

}).call(this);
