// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.ListCabView = (function(superClass) {
    extend(ListCabView, superClass);

    function ListCabView() {
      return ListCabView.__super__.constructor.apply(this, arguments);
    }

    ListCabView.prototype.container = "section#booking article#list-events ul";

    ListCabView.prototype.template_url = "/app/templates/listCab.mustache";

    return ListCabView;

  })(Monocle.View);

}).call(this);
