// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalTaskPersonView = (function(superClass) {
    extend(LocalTaskPersonView, superClass);

    function LocalTaskPersonView() {
      return LocalTaskPersonView.__super__.constructor.apply(this, arguments);
    }

    LocalTaskPersonView.prototype.container = "section#taskSelectPerson article#taskPerson-form ul";

    LocalTaskPersonView.prototype.template_url = "/app/templates/localTaskPerson.mustache";

    LocalTaskPersonView.prototype.events = {
      "singleTap li": "onSelect"
    };

    LocalTaskPersonView.prototype.onSelect = function(event) {
      var liTarget;
      liTarget = $$(event.currentTarget);
      if (liTarget.hasClass("cancel")) {
        liTarget.removeClass("cancel");
        liTarget.addClass("accept");
        liTarget.addClass("theme");
        __Controller.TaskSelectPerson.selectCount++;
      } else {
        liTarget.removeClass("accept");
        liTarget.removeClass("theme");
        liTarget.addClass("cancel");
        __Controller.TaskSelectPerson.selectCount--;
      }
      return FacadeCore.prototype.count("a[data-action=reset]", __Controller.TaskSelectPerson.selectCount);
    };

    return LocalTaskPersonView;

  })(Monocle.View);

}).call(this);
