// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalTaskCombiView = (function(superClass) {
    extend(LocalTaskCombiView, superClass);

    function LocalTaskCombiView() {
      return LocalTaskCombiView.__super__.constructor.apply(this, arguments);
    }

    LocalTaskCombiView.prototype.container = "section#newLocalTask article#localTaskCombi-form ul";

    LocalTaskCombiView.prototype.template_url = "/app/templates/localTaskCombi.mustache";

    LocalTaskCombiView.prototype.events = {
      "singleTap button": "onRemove"
    };

    LocalTaskCombiView.prototype.onRemove = function(event) {
      return this.remove();
    };

    return LocalTaskCombiView;

  })(Monocle.View);

}).call(this);
