// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalTaskInvSelectView = (function(superClass) {
    extend(LocalTaskInvSelectView, superClass);

    function LocalTaskInvSelectView() {
      return LocalTaskInvSelectView.__super__.constructor.apply(this, arguments);
    }

    LocalTaskInvSelectView.prototype.container = "section#newInvoice article#invoiceTaskSelect-form ul";

    LocalTaskInvSelectView.prototype.template_url = "/app/templates/localTaskInvSelect.mustache";

    return LocalTaskInvSelectView;

  })(Monocle.View);

}).call(this);
