// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalSelectView = (function(superClass) {
    extend(LocalSelectView, superClass);

    function LocalSelectView() {
      return LocalSelectView.__super__.constructor.apply(this, arguments);
    }

    LocalSelectView.prototype.container = "section#booking article#list-local ul";

    LocalSelectView.prototype.template_url = "/app/templates/localSelect.mustache";

    LocalSelectView.prototype.events = {
      "singleTap li": "selectLocal"
    };

    LocalSelectView.prototype.selectLocal = function(event) {
      var local;
      local = __FacadeCore.Cache_get(appName + "local");
      if (!local || (local && local.id !== this.model.locId)) {
        __FacadeCore.Storage_set(appName + "localId", null);
        __FacadeCore.Storage_set(appName + "localId", this.model.locId);
        return localReady();
      }
    };

    return LocalSelectView;

  })(Monocle.View);

}).call(this);
