// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalTaskCombiFirstView = (function(superClass) {
    extend(LocalTaskCombiFirstView, superClass);

    function LocalTaskCombiFirstView() {
      return LocalTaskCombiFirstView.__super__.constructor.apply(this, arguments);
    }

    LocalTaskCombiFirstView.prototype.container = "section#newLocalTask article#localTaskCombi-form ul";

    LocalTaskCombiFirstView.prototype.template_url = "/app/templates/localTaskCombiFirst.mustache";

    return LocalTaskCombiFirstView;

  })(Monocle.View);

}).call(this);
