// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalTaskInvView = (function(superClass) {
    extend(LocalTaskInvView, superClass);

    function LocalTaskInvView() {
      return LocalTaskInvView.__super__.constructor.apply(this, arguments);
    }

    LocalTaskInvView.prototype.container = "section#newInvoice article#invoiceTaskSelect-form ul";

    LocalTaskInvView.prototype.template_url = "/app/templates/localTaskInv.mustache";

    LocalTaskInvView.prototype.events = {
      "singleTap li": "onSelect"
    };

    LocalTaskInvView.prototype.onSelect = function(event) {
      var selectedTasksBilNum;
      this.model.updateAttributes({
        enabled: this.model.enabled ? false : true
      });
      this.refresh();
      selectedTasksBilNum = __FacadeCore.Cache_get(appName + "selectedTasksBilNum");
      __FacadeCore.Cache_remove(appName + "bilTaskId" + selectedTasksBilNum);
      __FacadeCore.Cache_set(appName + "bilTaskId" + selectedTasksBilNum, this.model);
      __FacadeCore.Cache_remove(appName + "selectedTasksBilType");
      return __FacadeCore.Router_article("newInvoice", "invoice-form");
    };

    return LocalTaskInvView;

  })(Monocle.View);

}).call(this);
