// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.LocalTaskNameView = (function(superClass) {
    extend(LocalTaskNameView, superClass);

    function LocalTaskNameView() {
      return LocalTaskNameView.__super__.constructor.apply(this, arguments);
    }

    LocalTaskNameView.prototype.container = "section#newLocalTask article#localTask-form #localTask-name";

    LocalTaskNameView.prototype.template_url = "/app/templates/localTaskName.mustache";

    return LocalTaskNameView;

  })(Monocle.View);

}).call(this);
