// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.ProductNameView = (function(superClass) {
    extend(ProductNameView, superClass);

    function ProductNameView() {
      return ProductNameView.__super__.constructor.apply(this, arguments);
    }

    ProductNameView.prototype.container = "section#newProduct article#product-form #product-name";

    ProductNameView.prototype.template_url = "/app/templates/productName.mustache";

    return ProductNameView;

  })(Monocle.View);

}).call(this);
