// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.SearchTypeView = (function(superClass) {
    extend(SearchTypeView, superClass);

    function SearchTypeView() {
      return SearchTypeView.__super__.constructor.apply(this, arguments);
    }

    SearchTypeView.prototype.container = "section#searchClient article#search-clients ul";

    SearchTypeView.prototype.template_url = "/app/templates/searchType.mustache";

    return SearchTypeView;

  })(Monocle.View);

}).call(this);
