// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.SearchListView = (function(superClass) {
    extend(SearchListView, superClass);

    function SearchListView() {
      return SearchListView.__super__.constructor.apply(this, arguments);
    }

    SearchListView.prototype.container = "section#booking article#list-clients ul";

    SearchListView.prototype.template_url = "/app/templates/searchType.mustache";

    return SearchListView;

  })(Monocle.View);

}).call(this);
