// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.TaskSelectButtonView = (function(superClass) {
    extend(TaskSelectButtonView, superClass);

    function TaskSelectButtonView() {
      return TaskSelectButtonView.__super__.constructor.apply(this, arguments);
    }

    TaskSelectButtonView.prototype.container = "section#taskSelect article#task-form ul";

    TaskSelectButtonView.prototype.template_url = "/app/templates/taskSelectButton.mustache";

    return TaskSelectButtonView;

  })(Monocle.View);

}).call(this);
