// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.TaskSelectCalendarView = (function(superClass) {
    extend(TaskSelectCalendarView, superClass);

    function TaskSelectCalendarView() {
      return TaskSelectCalendarView.__super__.constructor.apply(this, arguments);
    }

    TaskSelectCalendarView.prototype.container = "section#taskSelect article#task-form ul";

    TaskSelectCalendarView.prototype.template_url = "/app/templates/taskSelectCalendar.mustache";

    return TaskSelectCalendarView;

  })(Monocle.View);

}).call(this);
