// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.TaskSelectView = (function(superClass) {
    extend(TaskSelectView, superClass);

    function TaskSelectView() {
      return TaskSelectView.__super__.constructor.apply(this, arguments);
    }

    TaskSelectView.prototype.container = "section#taskSelect article#task-form ul";

    TaskSelectView.prototype.template_url = "/app/templates/taskSelect.mustache";

    TaskSelectView.prototype.events = {
      "singleTap li": "onTasksPer"
    };

    TaskSelectView.prototype.onTasksPer = function(event) {
      if (this.model.tasMultiple) {
        __FacadeCore.Cache_remove(appName + "selectedTasksPerNum");
        __FacadeCore.Cache_set(appName + "selectedTasksPerNum", this.model.tasSelId);
        return __FacadeCore.Router_article("taskSelectPerson", "taskPerson-form");
      }
    };

    return TaskSelectView;

  })(Monocle.View);

}).call(this);
