// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.TaskSelectGoodsView = (function(superClass) {
    extend(TaskSelectGoodsView, superClass);

    function TaskSelectGoodsView() {
      return TaskSelectGoodsView.__super__.constructor.apply(this, arguments);
    }

    TaskSelectGoodsView.prototype.container = "section#taskSelect article#task-form ul";

    TaskSelectGoodsView.prototype.template_url = "/app/templates/taskSelectGoods.mustache";

    return TaskSelectGoodsView;

  })(Monocle.View);

}).call(this);
