// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.TimesHoursView = (function(superClass) {
    extend(TimesHoursView, superClass);

    function TimesHoursView() {
      return TimesHoursView.__super__.constructor.apply(this, arguments);
    }

    TimesHoursView.prototype.container = "section#newHours article#hours-form ul";

    TimesHoursView.prototype.template_url = "/app/templates/timesHours.mustache";

    TimesHoursView.prototype.events = {
      "singleTap button": "onRemove"
    };

    TimesHoursView.prototype.onRemove = function(event) {
      return this.remove();
    };

    return TimesHoursView;

  })(Monocle.View);

}).call(this);
