// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  __View.TimesHoursCabView = (function(superClass) {
    extend(TimesHoursCabView, superClass);

    function TimesHoursCabView() {
      return TimesHoursCabView.__super__.constructor.apply(this, arguments);
    }

    TimesHoursCabView.prototype.container = "section#newHours article#hours-form ul";

    TimesHoursCabView.prototype.template_url = "/app/templates/timesHoursCab.mustache";

    return TimesHoursCabView;

  })(Monocle.View);

}).call(this);
